
services:
  web:
    build: .
    container_name: weatherbot
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_BOT_TOKEN: your_token
      WEATHER_API_KEY: your_key
      DATABASE_URL: postgresql+asyncpg://postgres:123@db/weatherbot
      WEBHOOK_URL: your_url
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: weatherbot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
